# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11nQDlZklgx7XuqWHAO9hugLmpN1PbmoW
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from warnings import filterwarnings
filterwarnings('ignore')

palette = sns.color_palette(['#023047', '#e85d04', '#0077b6', '#ff8200', '#0096c7', '#ff9c33'])


def analysis_plots(data, features, histplot=True, barplot=False,
                   outliers=False, boxplot=False, boxplot_x=None,
                   kde=False, hue=None, target=None,
                   color='#023047', figsize=(20, 12)):

    """
    Generate plots for univariate and bivariate analysis.
    """

        num_features = len(features)
        num_cols = 3
        num_rows = (num_features + num_cols - 1) // num_cols

        fig, axes = plt.subplots(num_rows, num_cols, figsize=figsize)

        axes = np.array(axes).reshape(num_rows, num_cols)

        for i, feature in enumerate(features):

            row = i // num_cols
            col = i % num_cols
            ax = axes[row, col]

            # ---------------------------
            # BARPLOT (categorical frequency)
            # ---------------------------
            if barplot and target is None:

                counts = data[feature].value_counts(normalize=True).sort_values() * 100

                ax.barh(counts.index.astype(str), counts.values, color=color)

                for idx, value in enumerate(counts.values):
                    ax.text(value + 0.5, idx, f'{value:.1f}%', va='center', fontsize=11)

                ax.tick_params(axis='x', bottom=False, labelbottom=False)
                ax.spines['top'].set_visible(False)
                ax.spines['right'].set_visible(False)
                ax.grid(False)

            # ---------------------------
            # BARPLOT BIVARIADO (ex: Survival)
            # ---------------------------
            elif barplot and target is not None:

                sns.barplot(data=data, x=feature, y=target, ax=ax, color=color)

            # ---------------------------
            # OUTLIER BOXPLOT
            # ---------------------------
            elif outliers:

                sns.boxplot(data=data, x=feature, ax=ax, color=color)

            # ---------------------------
            # BOXPLOT BIVARIADO
            # ---------------------------
            elif boxplot:

                sns.boxplot(data=data, x=boxplot_x, y=feature, showfliers=outliers, ax=ax, palette=palette)

            # ---------------------------
            # HISTOGRAM
            # ---------------------------
            else:

                sns.histplot(data=data, x=feature, kde=kde, hue=hue, stat='proportion', ax=ax, color=color)

            ax.set_title(feature, fontsize=13, pad=15)
            ax.set_xlabel('')

        # remover subplots vazios
        for j in range(num_features, len(axes.flat)):
            fig.delaxes(axes.flat[j])

        plt.subplots_adjust(
            left=0.08, right=0.95, top=0.92, bottom=0.08,
            wspace=0.35, hspace=0.45
        )

        plt.show()

def check_outliers(data, features):
    '''
    Check for outliers in the given dataset features.

    This function calculates and identifies outliers in the specified features
    using the Interquartile Range (IQR) method.

    Args:
        data (DataFrame): The DataFrame containing the data to check for outliers.
        features (list): A list of feature names to check for outliers.

    Returns:
        tuple: A tuple containing three elements:
            - outlier_indexes (dict): A dictionary mapping feature names to lists of outlier indexes.
            - outlier_counts (dict): A dictionary mapping feature names to the count of outliers.
            - total_outliers (int): The total count of outliers in the dataset.

    Raises:
        CustomException: If an error occurs while checking for outliers.

    '''

    try:

        outlier_counts = {}
        outlier_indexes = {}
        total_outliers = 0

        for feature in features:
            Q1 = data[feature].quantile(0.25)
            Q3 = data[feature].quantile(0.75)

            IQR = Q3 - Q1

            lower_bound = Q1 - 1.5 * IQR
            upper_bound = Q3 + 1.5 * IQR

            feature_outliers = data[(data[feature] < lower_bound) | (data[feature] > upper_bound)]
            outlier_indexes[feature] = feature_outliers.index.tolist()
            outlier_count = len(feature_outliers)
            outlier_counts[feature] = outlier_count
            total_outliers += outlier_count

        print(f'There are {total_outliers} outliers in the dataset.')
        print()
        print(f'Number (percentage) of outliers per feature: ')
        print()
        for feature, count in outlier_counts.items():
            print(f'{feature}: {count} ({round(count/len(data)*100, 2)})%')

        return outlier_indexes, outlier_counts, total_outliers

    except Exception as e:
        raise CustomException(e, sys)