# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11nQDlZklgx7XuqWHAO9hugLmpN1PbmoW
"""

# ============================================================================
# PRÉ-PROCESSAMENTO MANUAL (SEM PIPELINES - HOLD-OUT)
# ============================================================================

def preprocess_data_holdout(X_train, X_val):
    """
    Pré-processar dados manualmente para Hold-Out.
    FIT no treino, TRANSFORM no teste (evitar data leakage).
    """
    # Criar cópias
    X_train_proc = X_train.copy()
    X_val_proc = X_val.copy()

    # Armazenar transformers
    transformers = {}

    # 1. Age: imputação + StandardScaler
    age_imputer = SimpleImputer(strategy='median')
    age_scaler = StandardScaler()

    X_train_proc['Age'] = age_imputer.fit_transform(X_train_proc[['Age']])[:, 0]
    X_val_proc['Age'] = age_imputer.transform(X_val_proc[['Age']])[:, 0]

    X_train_proc['Age'] = age_scaler.fit_transform(X_train_proc[['Age']])[:, 0]
    X_val_proc['Age'] = age_scaler.transform(X_val_proc[['Age']])[:, 0]

    transformers['age_imputer'] = age_imputer
    transformers['age_scaler'] = age_scaler

    # 2. Fare: imputação + MinMaxScaler
    fare_imputer = SimpleImputer(strategy='median')
    fare_scaler = MinMaxScaler()

    X_train_proc['Fare'] = fare_imputer.fit_transform(X_train_proc[['Fare']])[:, 0]
    X_val_proc['Fare'] = fare_imputer.transform(X_val_proc[['Fare']])[:, 0]

    X_train_proc['Fare'] = fare_scaler.fit_transform(X_train_proc[['Fare']])[:, 0]
    X_val_proc['Fare'] = fare_scaler.transform(X_val_proc[['Fare']])[:, 0]

    transformers['fare_imputer'] = fare_imputer
    transformers['fare_scaler'] = fare_scaler

    # 3. Sex: imputação + OrdinalEncoder
    sex_imputer = SimpleImputer(strategy='most_frequent')
    sex_encoder = OrdinalEncoder(categories=[['female', 'male']], dtype=int)

    X_train_proc['Sex'] = sex_imputer.fit_transform(X_train_proc[['Sex']])[:, 0]
    X_val_proc['Sex'] = sex_imputer.transform(X_val_proc[['Sex']])[:, 0]

    X_train_proc['Sex'] = sex_encoder.fit_transform(X_train_proc[['Sex']])[:, 0]
    X_val_proc['Sex'] = sex_encoder.transform(X_val_proc[['Sex']])[:, 0]

    transformers['sex_imputer'] = sex_imputer
    transformers['sex_encoder'] = sex_encoder

    # 4. Embarked: imputação + OneHotEncoder
    embarked_imputer = SimpleImputer(strategy='most_frequent')
    embarked_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

    X_train_proc['Embarked'] = embarked_imputer.fit_transform(X_train_proc[['Embarked']])[:, 0]
    X_val_proc['Embarked'] = embarked_imputer.transform(X_val_proc[['Embarked']])[:, 0]

    embarked_train = embarked_encoder.fit_transform(X_train_proc[['Embarked']])
    embarked_val = embarked_encoder.transform(X_val_proc[['Embarked']])

    embarked_cols = [f'Embarked_{cat}' for cat in embarked_encoder.categories_[0]]

    transformers['embarked_imputer'] = embarked_imputer
    transformers['embarked_encoder'] = embarked_encoder
    transformers['embarked_cols'] = embarked_cols

    # 5. Pclass: OneHotEncoder
    pclass_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

    pclass_train = pclass_encoder.fit_transform(X_train_proc[['Pclass']])
    pclass_val = pclass_encoder.transform(X_val_proc[['Pclass']])

    pclass_cols = [f'Pclass_{cat}' for cat in pclass_encoder.categories_[0]]

    transformers['pclass_encoder'] = pclass_encoder
    transformers['pclass_cols'] = pclass_cols

    # 6. Remover colunas originais e adicionar encoded
    cols_to_drop = ['Embarked', 'Pclass']
    X_train_proc = X_train_proc.drop(columns=cols_to_drop)
    X_val_proc = X_val_proc.drop(columns=cols_to_drop)

    # Adicionar colunas one-hot
    embarked_df_train = pd.DataFrame(embarked_train, columns=embarked_cols, index=X_train_proc.index)
    embarked_df_val = pd.DataFrame(embarked_val, columns=embarked_cols, index=X_val_proc.index)

    pclass_df_train = pd.DataFrame(pclass_train, columns=pclass_cols, index=X_train_proc.index)
    pclass_df_val = pd.DataFrame(pclass_val, columns=pclass_cols, index=X_val_proc.index)

    X_train_proc = pd.concat([X_train_proc, embarked_df_train, pclass_df_train], axis=1)
    X_val_proc = pd.concat([X_val_proc, embarked_df_val, pclass_df_val], axis=1)

    print(f"Colunas após pré-processamento: {X_train_proc.columns.tolist()}")
    print(f"Shape X_train_proc: {X_train_proc.shape}")
    print(f"Shape X_val_proc: {X_val_proc.shape}")

    return X_train_proc, X_val_proc, transformers

import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    roc_curve,
    confusion_matrix,
    classification_report
)

# ======================================================
# CONFIGURAÇÕES GLOBAIS
# ======================================================

COLORS = {
    "dark": "#023047",
    "blue": "#0077b6",
    "light_blue": "#00b4d8",
    "soft": "#90e0ef",
    "orange": "#e85d04"
}

# ======================================================
# TREINAMENTO E AVALIAÇÃO
# ======================================================

def fit_models(models, X_train, y_train, X_val, y_val):
    """
    Treina e avalia os modelos.
    Retorna os modelos treinados e o DataFrame de resultados.
    """
    trained_models = {}
    results = []

    for name, model in models.items():
        start = time.time()
        model.fit(X_train, y_train)
        train_time = time.time() - start

        trained_models[name] = model

        y_train_pred = model.predict(X_train)
        y_val_pred = model.predict(X_val)

        train_acc = accuracy_score(y_train, y_train_pred)
        val_acc = accuracy_score(y_val, y_val_pred)

        results.append({
            "model": name,
            "train_accuracy": train_acc,
            "val_accuracy": val_acc,
            "overfitting_gap": train_acc - val_acc,
            "training_time": train_time
        })

    results_df = pd.DataFrame(results).sort_values(
        "val_accuracy",
        ascending=False
    ).reset_index(drop=True)

    return trained_models, results_df


# ======================================================
# PLOTAGEM E RELATÓRIOS
# ======================================================

def plot_performance(results):
    """Plota comparação de performance usando o DataFrame de resultados."""
    df = results

    x = np.arange(len(df))
    bar_width = 0.35

    fig, ax = plt.subplots(figsize=(12, 6))

    train_bars = ax.bar(
        x - bar_width/2,
        df["train_accuracy"],
        bar_width,
        label="Training Accuracy",
        color=COLORS["blue"]
    )

    val_bars = ax.bar(
        x + bar_width/2,
        df["val_accuracy"],
        bar_width,
        label="Validation Accuracy",
        color=COLORS["dark"]
    )

    ax.set_xlabel("Model", fontsize=12, loc="left")
    ax.set_ylabel("Accuracy", fontsize=12, loc="top")

    ax.set_title(
        "Model Performance Comparison",
        fontsize=14,
        fontweight="bold",
        loc="left",
        pad=20
    )

    ax.set_xticks(x)
    ax.set_xticklabels(df["model"], rotation=45, ha="right")

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    ax.grid(axis="y", alpha=0.3)

    for bar in train_bars + val_bars:
        height = bar.get_height()
        ax.annotate(
            f"{height:.2f}",
            xy=(bar.get_x() + bar.get_width()/2, height),
            xytext=(0, 3),
            textcoords="offset points",
            ha="center",
            va="bottom",
            fontsize=9
        )

    ax.legend(loc="lower right")

    plt.tight_layout()
    plt.show()


def plot_confusion_matrices(trained_models, X_val, y_val):
    """Plota matrizes de confusão para cada modelo treinado."""
    n = len(trained_models)

    fig, axes = plt.subplots(1, n, figsize=(5*n, 4))

    if n == 1:
        axes = [axes]

    for ax, (name, model) in zip(axes, trained_models.items()):
        y_pred = model.predict(X_val)
        cm = confusion_matrix(y_val, y_pred)

        sns.heatmap(
            cm,
            annot=True,
            fmt="d",
            cmap="Blues",
            ax=ax,
            cbar_kws={"label": "Count"}
        )

        ax.set_title(f"Confusion Matrix - {name}", fontweight="bold")
        ax.set_xlabel("Predicted")
        ax.set_ylabel("Actual")
        ax.set_xticklabels(["Not Survived", "Survived"])
        ax.set_yticklabels(["Not Survived", "Survived"])

    plt.tight_layout()
    plt.show()


def plot_roc_curves(trained_models, X_val, y_val):
    """Plota curvas ROC para cada modelo treinado."""
    fig, ax = plt.subplots(figsize=(8, 6))

    colors = [
        COLORS["dark"],
        COLORS["blue"],
        COLORS["light_blue"],
        COLORS["soft"]
    ]

    for i, (name, model) in enumerate(trained_models.items()):
        y_proba = model.predict_proba(X_val)[:, 1]
        fpr, tpr, _ = roc_curve(y_val, y_proba)
        auc_score = roc_auc_score(y_val, y_proba)

        ax.plot(
            fpr, tpr, linewidth=2,
            color=colors[i % len(colors)],
            label=f"{name} (AUC={auc_score:.3f})"
        )

    ax.plot(
        [0, 1], [0, 1], linestyle="--",
        color=COLORS["orange"], linewidth=2,
        label="Random Classifier"
    )

    ax.set_xlabel("False Positive Rate")
    ax.set_ylabel("True Positive Rate")
    ax.set_title("ROC Curves - Model Comparison", fontweight="bold")
    ax.legend(loc="lower right")
    ax.grid(alpha=0.3)

    plt.tight_layout()
    plt.show()


def print_classification_reports(trained_models, X_val, y_val):
    """Imprime classification report para cada modelo."""
    for name, model in trained_models.items():
        y_pred = model.predict(X_val)
        print(f"\n{name}")
        print("-" * 40)
        print(classification_report(y_val, y_pred))